In [3]:
pip install numpy

Requirement already satisfied: numpy in c:\users\admin\anaconda3\envs\ml\lib\site-packages (2.2.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np

In [7]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)#converts that list into a NumPy array
type(arr)# it tell data type

numpy.ndarray

In [9]:
arr.shape # it gives you number of rows and columns in your array

(5,)

In [17]:
## multinested array
my_list1=[1,2,3,4]
my_list2=[5,4,3,6]
my_list3=[9,4,8,3]
arr=np.array([my_list1,my_list2,my_list3])# when we convert our more than one list to array in numpy than that all list must have same number of columns
arr

array([[1, 2, 3, 4],
       [5, 4, 3, 6],
       [9, 4, 8, 3]])

In [19]:
arr.shape  #it gives number of rows and column present in your 2-d array.

(3, 4)

In [23]:
# reshape() 
arr = np.array([1,2,3,4,5,6])
arr.shape 
new_arr = arr.reshape(2, 3)
new_arr
#new_arr.shape ->(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#  INDEXING IN NUMPY
arr=np.array([1,2,3,4,5,6])
arr[3] # Accessing element from 1D Array 
arr.ndim # it tell us is array 1D or 2D (If 1 → 1D array,If 2 → 2D array)
arr=arr.reshape(2,3)

In [45]:
arr[:,:] # To access all elements of 2D array
arr[0:1,0:2] # 0:1 is for 0 row and 0:2 is for 0 to 1 col 
arr[0:,1:]

array([[2, 3],
       [5, 6]])

In [47]:
# Inbuilt function in Numpy
# np.arange(start, stop, step) it create an array with evenly spaced values in a range
# start=0(default),step=1(default)
np.arange(5)

array([0, 1, 2, 3, 4])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
# np.linspace() Generate evenly spaced numbers between two values,with a fixed count
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
#copy() function  and broadcasting
arr=np.array([1,2,3,4,5,6,7,8])
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100])

In [59]:
arr1=arr
arr1[3:]=500 # in this both array point to same memory so any change in duplicate array will reflected to original one also
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500])

In [61]:
arr1=arr.copy()#Best way to copy any array it point to another memory not the same as original
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500])

In [63]:
#what is broadcasting ->Numpy automatically expands smaller arrays to match bigger arrays during operations.
arr=np.array([1,2,3,4])
arr+10
# here 
#10 is broadcast to -> [10, 10, 10, 10] then ele-wise addition happens.

array([11, 12, 13, 14])

In [65]:
#Broadcasting with 2D + 1D
arr=np.array([[1,2,3],[4,5,6]])
b=np.array([10, 20, 30])
arr + b

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# Broadcasting rules (interview favorite 🔑)

# Two shapes are compatible if:

# Compare from right to left

# Dimensions are equal or one of them is 1

# 1️⃣ (2, 3) and (3,) → ✅ Works

# Shapes:

# A = (2, 3)

# B = (3,) → treat as (1, 3)

# Compare from right:

# A:   2   3
# B:   1   3
#       ↑   ↑
#      ok  ok


# 3 and 3 → equal ✅

#2 and 1 → one is 1 → ok ✅

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
import pandas as pd
import numpy as np

#Create sample DataFrame
data = {
    'Name': ['Amit', 'Ravi', 'Neha', 'Amit', 'Sita'],
    'Age': [25, 40, None, 25, -5],
    'Salary': [30000, 50000, 40000, 30000, 70000],
    'City': ['Pune', 'Mumbai', 'Pune', 'Pune', 'Delhi']
}

df = pd.DataFrame(data)
df

   Name   Age  Salary    City
0  Amit  25.0   30000    Pune
1  Ravi  40.0   50000  Mumbai
2  Neha   NaN   40000    Pune
3  Amit  25.0   30000    Pune
4  Sita  -5.0   70000   Delhi

In [6]:
# shape,size and dimensions
df.shape

(5, 4)

In [8]:
df.size # no. of elements in df

20

In [10]:
df.ndim # is it 1-D or 2-D

2

In [12]:
# Column names and data types
df.columns

Index(['Name', 'Age', 'Salary', 'City'], dtype='object')

In [14]:
df.dtypes

Name       object
Age       float64
Salary      int64
City       object
dtype: object

In [16]:
#Missing Values
df.isnull()

    Name    Age  Salary   City
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3  False  False   False  False
4  False  False   False  False

In [18]:
df.isnull().sum() # it will give count of null values in each columns

Name      0
Age       1
Salary    0
City      0
dtype: int64

In [22]:
#Duplicated rows
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [26]:
df.duplicated().sum()

np.int64(1)

In [30]:
# Satistical Summary
df.describe()

             Age        Salary
count   4.000000      5.000000
mean   21.250000  44000.000000
std    18.874586  16733.200531
min    -5.000000  30000.000000
25%    17.500000  30000.000000
50%    25.000000  40000.000000
75%    28.750000  50000.000000
max    40.000000  70000.000000

In [32]:
df['Age'].describe()

count     4.000000
mean     21.250000
std      18.874586
min      -5.000000
25%      17.500000
50%      25.000000
75%      28.750000
max      40.000000
Name: Age, dtype: float64

In [40]:
df['Salary'].describe()

count        5.000000
mean     44000.000000
std      16733.200531
min      30000.000000
25%      30000.000000
50%      40000.000000
75%      50000.000000
max      70000.000000
Name: Salary, dtype: float64

In [44]:
df['Age'].mean() # like this you can just print only count or mean....so on

np.float64(21.25)

In [46]:
#Conditional filtering
df[df['Age']>30]

   Name   Age  Salary    City
1  Ravi  40.0   50000  Mumbai

In [48]:
df[(df['Age']>20) & (df['Salary']<50000) ]

   Name   Age  Salary  City
0  Amit  25.0   30000  Pune
3  Amit  25.0   30000  Pune

In [50]:
#Unique values & counts
df['City'].unique()

array(['Pune', 'Mumbai', 'Delhi'], dtype=object)

In [60]:
#np.ones(shape, dtype=float)

np.ones((7,3)) # for 2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [64]:
np.ones((2,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [70]:
# np.random.rand(...)  it is Uniformly distributed between 0 and 1
np.random.rand(5)

array([0.24817147, 0.50522621, 0.05316309, 0.15436787, 0.19055796])

In [72]:
np.random.rand(2, 3)

array([[0.06629817, 0.21412229, 0.26101278],
       [0.03501037, 0.80133878, 0.47594944]])

In [74]:
# np.random.randn() it can be negative or greater than 1 or most values are near 0
np.random.randn(5)

array([-0.99256797,  0.92387111,  2.38740349,  0.54979311, -0.16001893])

In [76]:
np.random.randn(2, 3)

array([[-0.80566678,  1.23402905, -0.91475568],
       [ 0.2799559 ,  0.17933717, -0.08809963]])

In [78]:
#Generate random integers in a given range
#np.random.randint(low, high, size) low=minimum value it is inclusive,high=maximum value it is exclusive,size=shape of output array(it is optional)
np.random.randint(1, 10)

5

In [80]:
np.random.randint(1, 10, 5)

array([3, 8, 5, 2, 5], dtype=int32)

In [84]:
# 2D array
np.random.randint(0,5,(3,4))

array([[0, 4, 4, 4],
       [2, 3, 1, 3],
       [4, 3, 3, 0]], dtype=int32)

In [86]:
#np.random.random_sample()
# Generate random floating-point numbers from Uniform(0, 1)
np.random.random_sample()

0.5693482350132203

In [88]:
np.random.random_sample(5)

array([0.78324794, 0.34596679, 0.16541203, 0.52439791, 0.87601129])

In [90]:
np.random.random_sample((2, 3))

array([[0.14199987, 0.71679141, 0.4862158 ],
       [0.14842091, 0.46918398, 0.45755504]])