In [1]:
# Learning Pandas
# It help to read,store,clean and analyze as well as summarize data
#Main Data structure in pandas
# 1)DataFrame- 2D data(like table with rows and col)
import pandas as pd
import numpy as np

In [9]:
## working with DataFrame
df=pd.DataFrame(
    np.arange(0,12).reshape(4,3),
    index=['Row1', 'Row2', 'Row3', 'Row4'],
    columns=['col1', 'col2', 'col3']

)

print(df)

      col1  col2  col3
Row1     0     1     2
Row2     3     4     5
Row3     6     7     8
Row4     9    10    11

In [11]:
# to_csv() is used to save your df into a csv file
# csv=comma separated values
# Basic syntax is df.to_csv("filename.csv)
df.to_csv("Test1.csv")

In [13]:
#Accessing the elements from dataframe -> there are two ways to do this
# first way
df.loc['Row1'] # to acces row

col1    0
col2    1
col3    2
Name: Row1, dtype: int64

In [15]:
type(df.loc['Row1']) # Dataframe is combination of series

pandas.core.series.Series

In [17]:
df["col1"]

Row1    0
Row2    3
Row3    6
Row4    9
Name: col1, dtype: int64

In [19]:
df.iloc[0:2,0:2] # for both row and col

      col1  col2
Row1     0     1
Row2     3     4

In [21]:
df.iloc[:,1:]

      col2  col3
Row1     1     2
Row2     4     5
Row3     7     8
Row4    10    11

In [23]:
#converting Dataframe into Array
# old way 
df.iloc[:,1:].values

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [25]:
# new and modern way to converting df to Array
arr = df.to_numpy()
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [27]:
# To check Null Values in Entire df
df.isnull()

       col1   col2   col3
Row1  False  False  False
Row2  False  False  False
Row3  False  False  False
Row4  False  False  False

In [29]:
#Count Null Values Column-wise
df.isnull().sum()

col1    0
col2    0
col3    0
dtype: int64

In [31]:
# return all unique val present in column
df['col1'].unique()

array([0, 3, 6, 9])

In [33]:
# count of unique val
df['col1'].nunique()

4

In [35]:
#Accessing multi columns
df[['col1', 'col3']]

      col1  col3
Row1     0     2
Row2     3     5
Row3     6     8
Row4     9    11

In [37]:
df.loc[:, ['col1', 'col3']]

#: → means all rows

#['col1', 'col3'] → only these columns

      col1  col3
Row1     0     2
Row2     3     5
Row3     6     8
Row4     9    11

In [ ]:
df.iloc[:, [0, 2]]
#: → all rows

#[0, 2] → first and third column